version: "3"
services:
  app:
    container_name: iTitrate
    image: 696778203502.dkr.ecr.us-east-1.amazonaws.com/ititrate:${ARCH}
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES} 
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
